run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - goconst
    - gocyclo
    - misspell
    - prealloc
    - unconvert
    - unparam

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  gosec:
    excludes:
      - G117
  misspell:
    locale: US

issues:
  exclude-dirs:
    - site
  max-issues-per-linter: 50
  max-same-issues: 5
